name: Puppet Deployment
on:
  push:
    branches: [ main ]

jobs:
  Puppet:
    name: Deploy 
    runs-on: ubuntu-latest
    steps:
    - name: ssh into ec2
      uses: appleboy/ssh-action@master
      with:
        host: "13.234.111.51"
        username: ubuntu
        key: ${{ secrets.SECRET_KEY }}
        port: 22
        script: |
          sudo rm -r control
          git clone https://github.com/rajiv1506/control.git
          cd control
          sudo puppet apply ./manifests/site.pp --modulepath modules --hiera_config hiera.yaml